# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee5e6e4ce2d3e123ea839439b8a7683c94de56df398dd33e9a7c0c25c34be320d45aa47d622bfdf3307da096d3be0652e835009642a9eafdae6c67295b76355

test:
  secret_key_base: 62ace604a8ff7aa3772b24004a158d6b8b98e19da74f9ce8daa1340dce147e0af2f4200205db2adc3453889736a7e74eefb15856fbf604ac3b46f5e246f172b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
